### ISSUE TITLE
Prevent Crawling Duplicate URLs with and without Trailing Slashes

### ISSUE THREAD

**Issue by alea12** [laiso/site2pdf#4]
Thank you for the work! I've tested with my website and this fits well with my needs. One issue I had is that this tool crawls the same URL twice, with and without a trailing slash (/):

* https://example.com/faq
* https://example.com/faq/

This could be addressed by updating the conditions of uniqueSubLinks. If this looks good to you, I could submit a PR.

https://github.com/laiso/site2pdf/blob/c3385864ce69c6cac66d6160751cbeff2d73e71a/index.ts#L30-L39

**Comment by laiso** [comment]
@alea12 URL normalization is a great approach. I have been interested in this as well. Please go ahead and create a pull request. thank you.
